// frontreact/src/components/TheHeader.tsx
import { useNavigate } from 'react-router-dom';

const TheHeader = () => {

  const navigate = useNavigate();
  const handleClick = () => navigate('/');

  return (
      <div className="navbar sticky-top navbar-dark bg-dark px-3">
        <div className="d-flex gap-3 justify-content-between align-items-center">
          <h4 className="m-0 cursor-pointer text-gradient" onClick={handleClick}>Athens Cinemas</h4>
        </div>
      </div>
  )
}

export default TheHeader

// frontend/src/components/TheHeader.vue
<template>
  <div class="navbar sticky-top navbar-dark bg-dark px-3">
    <div class="d-flex gap-3 justify-content-between align-items-center">
      <i v-if="route.name === 'home'" class="bi bi-list fs-3 cursor-pointer" data-bs-toggle="offcanvas"
        data-bs-target="#homeViewDrawer" />
      <i v-else class="bi bi-arrow-left fs-3 cursor-pointer" @click="router.back" />
      <h4 class="m-0 cursor-pointer text-secondary" @click="router.push({ name: 'home' })">Athens Cinemas</h4>
    </div>
  </div>
</template>

<script setup>
import { useRouter, useRoute } from 'vue-router';

const router = useRouter();
const route = useRoute();
</script>
